server:
  port: 8080

spring:
  application:
    name: "@project.parent.artifactId@"
    version: "@project.version@"
  profiles:
    include:
      # TO enable italian documentations
      - swaggerIT

info:
  build:
    artifact: "@project.parent.artifactId@"
    name: "@project.parent.artifactId@"
    description: "@project.description@"
    version: "@project.version@"

error-manager:
  enabled: true

meda:
  core:
    sessioncontext:
      enabled: false

logging:
  level:
    it.gov.pagopa.tkm.ms.parretriever: DEBUG

core:
  parRetrieverService:
    getPar:
      scheduler: ${PAR_RETRIEVER_GET_PAR_SCHEDULER:0 * * * * *}