spring:
  application:
    name: Tkm Par Retriever ${INSTANCE_NUMBER:0}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /tkm-ms-par-retriever

logging:
  level:
    root: ${LOGGING_LEVEL:INFO}

core:
  parRetrieverService:
    getBinRange:
      scheduler: ${PAR_RETRIEVER_BIN_RANGE_SCHEDULER:0 * * * * *}

azure:
  keyvault:
    enabled: true
    client-id: ${AZURE_KEYVAULT_CLIENT_ID}
    client-key: ${AZURE_KEYVAULT_CLIENT_KEY}
    tenant-id: ${AZURE_KEYVAULT_TENANT_ID}
    uri: ${AZURE_KEYVAULT_URI}
  storage:
    default-endpoints-protocol: https
    account-name: ${AZURE_STORAGE_ACCOUNT_NAME}
    account-key: ${AZURE_STORAGE_ACCOUNT_KEY}
    blob-endpoint: ${AZURE_STORAGE_ENDPOINT}

keyvault:
  mastercardResponsePrivateKey: ${${profile:prod}-mastercardResponsePrivateKey}
  mastercardApiKey: ${${profile:prod}-mastercardApiKey}
  mastercardKeyStorePwd: ${${profile:prod}-mastercardKeyStorePwd}

blobstorage:
  mastercard:
    publicEncryptionKey: azure-blob://${BLOB_STORAGE_NAME}/Public-Key-Encrypt.crt
    signingKeyCert: azure-blob://${BLOB_STORAGE_NAME}/Get_PAR-sandbox.p12
