/*
 * Payment Account Reference Inquiry API
 * Merchants, Acquirers, or Digital Activity Customers (DACs) can use this service to query the PAR Vault to obtain a Payment Account Reference(PAR), from a Primary Account Number (PAN). PAR provides an industry-aligned approach designed to help link PAN-based transactions to transactions using associated payment tokens, without using the PAN as the linkage mechanism.
 *
 * The version of the OpenAPI document: 1.3
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.gov.pagopa.tkm.ms.parretriever.client.mastercard.api.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * structure of the getPaymentAccountReferenceResponseBeforeDecryption after decryption.
 */
@ApiModel(description = "structure of the getPaymentAccountReferenceResponseBeforeDecryption after decryption.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-04-15T11:20:33.252+02:00[Europe/Berlin]")
public class GetPaymentAccountReferenceResponse {
  public static final String SERIALIZED_NAME_RESPONSE_ID = "responseId";
  @SerializedName(SERIALIZED_NAME_RESPONSE_ID)
  private String responseId;

  public static final String SERIALIZED_NAME_ENCRYPTED_PAYLOAD = "encryptedPayload";
  @SerializedName(SERIALIZED_NAME_ENCRYPTED_PAYLOAD)
  private GetPaymentAccountReferenceResponseEncryptedPayload encryptedPayload;


  public GetPaymentAccountReferenceResponse responseId(String responseId) {
    
    this.responseId = responseId;
    return this;
  }

   /**
   * The id of the response sent.
   * @return responseId
  **/
  @ApiModelProperty(example = "123456", required = true, value = "The id of the response sent.")

  public String getResponseId() {
    return responseId;
  }


  public void setResponseId(String responseId) {
    this.responseId = responseId;
  }


  public GetPaymentAccountReferenceResponse encryptedPayload(GetPaymentAccountReferenceResponseEncryptedPayload encryptedPayload) {
    
    this.encryptedPayload = encryptedPayload;
    return this;
  }

   /**
   * Get encryptedPayload
   * @return encryptedPayload
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GetPaymentAccountReferenceResponseEncryptedPayload getEncryptedPayload() {
    return encryptedPayload;
  }


  public void setEncryptedPayload(GetPaymentAccountReferenceResponseEncryptedPayload encryptedPayload) {
    this.encryptedPayload = encryptedPayload;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetPaymentAccountReferenceResponse getPaymentAccountReferenceResponse = (GetPaymentAccountReferenceResponse) o;
    return Objects.equals(this.responseId, getPaymentAccountReferenceResponse.responseId) &&
        Objects.equals(this.encryptedPayload, getPaymentAccountReferenceResponse.encryptedPayload);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responseId, encryptedPayload);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetPaymentAccountReferenceResponse {\n");
    sb.append("    responseId: ").append(toIndentedString(responseId)).append("\n");
    sb.append("    encryptedPayload: ").append(toIndentedString(encryptedPayload)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

